### ISSUE TITLE
Object highlighting

### ISSUE THREAD

**Issue by atomiks** [atomiks/moonlight-vscode-theme#1]
Please vote 👍 or 👎 for this.

Objects get a pastel green color when property access is performed on them. I've tried various different colors and this seems to be the best color without conflicting with existing colors.

<img src="https://i.gyazo.com/1f343805062cb22063057f2da8e90392.png" alt="colors" height="500">

A possibility might also be for object property keys to use the lighter pastel green and objects to use the stronger green (reversed).

**Comment by rychkog** [comment]
IMO it is quite hard to distinguish "prop" and "obj.nested.objects" colors. Can you, please, add a "reversed" example screenshot as well?

**Comment by atomiks** [comment]
I've decided against this now! Especially `Moonlight II` which now has a new red color for constants so it makes it more colorful.

**Comment by rychkog** [comment]
@atomiks Thanks a lot for this theme - it's really beautiful and good for eyes!

**Comment by atomiks** [comment]
@rychkog glad you like it! 💙
