### ISSUE TITLE
Compatibility for Webstorm

### ISSUE THREAD

**Issue by SkylerStearns** [atomiks/moonlight-vscode-theme#13]
This looks like an amazing theme, but I have no idea how to get this into Webstorm. Is there a way to export this to a format that works with Webstorm?

**Comment by atomiks** [comment]
I'm not sure how Webstorm themes work and wouldn't have the ability/time to work on one, so I'm not sure unfortunately

**Comment by SkylerStearns** [comment]
No worries. I appreciate the response!
