### ISSUE TITLE
Wrong syntax highlighting color

### ISSUE THREAD

**Issue by SrAnthony** [atomiks/moonlight-vscode-theme#14]
![Screenshot from 2020-03-12 09-09-01](https://user-images.githubusercontent.com/14919996/76520258-53373400-6441-11ea-931a-c7773cd93978.png)

I just removed the ~/.vscode folder and install only the moonlight theme, still occurs.

**Comment by atomiks** [comment]
Have you got the experimental "semantic syntax highlighting" (or similar) turned on?

**Comment by SrAnthony** [comment]
Didn't know about it...
Setting editor.semanticHighlighting.enabled to false seems to solve the issue :)

**Comment by atomiks** [comment]
Seems like it's default in the new version :\

**Comment by atomiks** [comment]
I'll work on an update that better supports semantic highlighting 🙂  to be honest, the feature is really cool and I'd like to turn it on, I just need to fix some problems

**Comment by atomiks** [comment]
I don't think I can fix it myself. It's a problem with the implementation that VS Code will need to fix I think.

Ref: https://github.com/microsoft/vscode/issues/92308

Leaving this open until it gets fixed

**Comment by atomiks** [comment]
It's been fixed. It's disabled by default in the new update, add this to enable it:

```js
  "editor.tokenColorCustomizations": {
    "semanticHighlighting": true
  }
```

Works well in my brief experience. One thing that's not possible right now is distinguishing function calls and function declarations, which is possible in the regular TextMate grammars. Might open an issue...
