### ISSUE TITLE
contrast increase in actvity bar and status bar

### ISSUE THREAD

**Issue by FatTonyy** [atomiks/moonlight-vscode-theme#16]
background-color on moon theme looks cleaner than moon II, maybe it's my eyes

**Comment by atomiks** [comment]
It's more saturated/blue yes, and there's less contrast with the outer chrome and the editor — problem with it is makes blue colors harder to stand out, so I desaturated it in Moonlight II. Even Moonlight II feels too saturated for me sometimes 😂

**Comment by FatTonyy** [comment]
Lol it’s growing on me, anyway excellent theme
