### ISSUE TITLE
Original background of "preview.png"

### ISSUE THREAD

**Issue by Brettm12345** [atomiks/moonlight-vscode-theme#17]
I would love to get a copy of the background image you used in [preview.png](https://github.com/atomiks/moonlight-vscode-theme/blob/master/preview.png)

**Comment by atomiks** [comment]
I got it off Unsplash searching for "space" or "moon{light}" or something, I should have credited it 😅

**Comment by atomiks** [comment]
Preview is changing with https://github.com/atomiks/moonlight-vscode-theme/pull/52
