### ISSUE TITLE
bad back ground in linux

### ISSUE THREAD

**Issue by sorushsaghari** [atomiks/moonlight-vscode-theme#19]
![image](https://user-images.githubusercontent.com/38028950/80920332-5b965600-8d84-11ea-90fc-47177601824a.png)
As you see them has problem in Linux . also it 's not ok like windows.

**Comment by atomiks** [comment]
Have you updated to the latest VS Code version? This was a problem prior to the July 2019 update. If it's still like that, file a VS Code issue as it's only a hex color, can't be a problem with the theme exactly.
