### ISSUE TITLE
Bug?: "Moonlight II" now has all keywords in italics, basically it is the same as "Moonlight II Italic"

### ISSUE THREAD

**Issue by rychkog** [atomiks/moonlight-vscode-theme#2]
Seems like because of this commit
https://github.com/atomiks/moonlight-vscode-theme/commit/9becf594eca6ce5b8cb387dcdd6fb57e69c1ef12

**Comment by atomiks** [comment]
Yeah I don't know if an Italic theme should have all keywords in italics? It was intentional. I mean mainly it's for Operator Mono where people love the curly glyphs

**Comment by atomiks** [comment]
0.8.3
