### ISSUE TITLE
Hard to read status bar when running debugger.

### ISSUE THREAD

**Issue by AlexKvazos** [atomiks/moonlight-vscode-theme#22]
<img width="1920" alt="Screen Shot 2020-07-14 at 12 25 06" src="https://user-images.githubusercontent.com/4448627/87456873-25b7ee00-c5cd-11ea-97c8-93acf09056e5.png">

Can we change the status bar background to something darker when running the debugger?

Thank you very much for making such an awesome theme!

**Comment by AlexKvazos** [comment]
Forgot to mention, happy to do the PR.

**Comment by atomiks** [comment]
PR is welcome!

**Comment by AlexKvazos** [comment]
Let me know if I should do something else! Looking forward for a release.

**Comment by AlexKvazos** [comment]
@atomiks Any updates?
