### ISSUE TITLE
This theme makes my life happier every day.

### ISSUE THREAD

**Issue by baleeds** [atomiks/moonlight-vscode-theme#28]
I've been using it for 2 years now, and have migrated it to other applications, like my terminal and WebStorm.

Thanks!

**Comment by martinezguillaume** [comment]
man, that's the best theme of the world (2 years too and don't want to change at all)

**Comment by quarkquartet** [comment]
Same. The theme that can make me stay quiet and peaceful in tiring working.

**Comment by atomiks** [comment]
Thank you for the kind words ❤️ 

I know this is really late 😅; currently cleaning up this repo to do a new release.

**Comment by baleeds** [comment]
2.5 years later, but I’m still loving the theme with no urge to change 🥹

**Comment by baleeds** [comment]
> Same. The theme that can make me stay quiet and peaceful in tiring working. I would appreciate it if someone can offer a same theme for iTerm2.

@quarkquartet Here's the ones I use that's my own take on the moonlight theme. Change the extension from `json` to `itermcolors` to import.
[moonlight_II_itermcolors.json](https://github.com/atomiks/moonlight-vscode-theme/files/13980421/moonlight_II_itermcolors.json)
