### ISSUE TITLE
"Moonlight Italic" doesn't render all keywords in italic in a JavaScript file

### ISSUE THREAD

**Issue by imbsky** [atomiks/moonlight-vscode-theme#3]

**Comment by atomiks** [comment]
It's been like that since I created it, so maybe people will find different behavior confusing

I changed it for Moonlight II tho

**Comment by imbsky** [comment]
Oh, that makes sense. Do you plan to update Moonlight Italic?

**Comment by atomiks** [comment]
Since I no longer use the original Moonlight theme personally, not really unless people want to make PRs for it which I'll gladly accept. All new work by me will be done on Moonlight II.

**Comment by imbsky** [comment]
All right! Thanks for creating this theme!

**Comment by Brettm12345** [comment]
You can customize the theme yourself in the settings
