### ISSUE TITLE
Make line separators more visible

### ISSUE THREAD

**Issue by Norfeldt** [atomiks/moonlight-vscode-theme#31]
I absolutely love 💜 this theme - thank you 🙏

I frequently have to adjust the height of my terminal which I placed below my explorer and find it tricky to grab the lines. Is there any chance that we can have them just a tiny bit more visible?

<img width="762" alt="Screenshot 2021-12-16 at 12 07 32" src="https://user-images.githubusercontent.com/678806/146361980-226b7e9a-129d-41b9-869f-fbf3d3f993e2.png">

**Comment by atomiks** [comment]
Hi, any chance you could make a PR for this? I don't have much time to work on this theme currently. Thanks!

**Comment by NorfeldtAbtion** [comment]
I would love to contribute but have no experience - do you have some good instructions how to pull down a theme repo and develop it to make PRs?

**Comment by atomiks** [comment]
@NorfeldtAbtion I never actually looked into how to build a theme properly and did everything the "slow" way: manually reloading the window to see the changes and edited the current extension's theme file I had selected.

With that said, I'd clone the repo, install "Moonlight" extension and search for it in your `Users/<you>/.vscode/extensions` folder (on a Mac at least) and open up the currently selected theme JSON file. 

Make your desired edits and `cmd+shift+p` > Reload Window to see the changes. Once finished, copy/paste the whole edited extension file into the cloned repo source.

Reference is here: https://code.visualstudio.com/api/references/theme-color

**Comment by NorfeldtAbtion** [comment]
thank you for the tip @atomiks I have now made #32

**Comment by atomiks** [comment]
`v0.10.5`
