### ISSUE TITLE
Semantic colorization for Go

### ISSUE THREAD

**Issue by enkeyz** [atomiks/moonlight-vscode-theme#36]
I love the theme, but it's missing specific semantic colorization for Go language. Would you accept a patch? I tried to use the same colors - what I've seen for Javascript in the theme.

![image](https://user-images.githubusercontent.com/17646853/166919873-7037818e-f8b8-44ed-9918-22c8fefd75a5.png)

**Comment by atomiks** [comment]
Sure!

One thing that has also annoyed me is the Hovercard/Intellisense Tooltip having bad highlighting color. It's either that muddy brown or the white color that makes text not possible to read. Fixing that too would be amazing 🙏

**Comment by enkeyz** [comment]
Will do a PR at the weekend then. Thanks <3
