### ISSUE TITLE
Unused Property

### ISSUE THREAD

**Issue by saltsoftdrink** [atomiks/moonlight-vscode-theme#38]
"panel.dropBackground"
Remove this VS Code no longer supports this.

&

Try to **compress** the theme code.

Thank You 😄

**Comment by atomiks** [comment]
> "panel.dropBackground"
Remove this VS Code no longer supports this.

Does it cause any issues?

> Try to compress the theme code.

You mean minify the theme files before publishing them? I kinda like editing the files unminified in my `.extensions` folder locally.

**Comment by Samyak-Bumb** [comment]
Yes, it increases the file size
