### ISSUE TITLE
Glow for TypeScript files

### ISSUE THREAD

**Issue by mtliendo** [atomiks/moonlight-vscode-theme#44]
Love love love this extension! I get tons of questions on my YouTube videos whenever I use it!

Just a quick question on how to add support for typescript files--glow is enabled, but it seems to only be picked up in my JavaScript files. 

I'm sure it's something simple, but I'm not too experienced with modifying VS Code themes. 

Thanks again!

**Comment by atomiks** [comment]
It's possible the `mtk` token numbers have changed for TS files, and need to target different tokens:

> ⚠️ The mtk token numbers (11 and 12 above – which represent the two function colors) can change when the theme or VS Code version is updated, causing incorrect colors. When new releases arrive, make sure to visit the README for the updated stylesheet or make an issue if they change due to VS Code – I will update them accordingly.

In your stylesheet, you can edit these numbers and see what tokens it affects. I can't remember how to inspect them though.
