### ISSUE TITLE
Color tag in Vue Js

### ISSUE THREAD

**Issue by RendraAndriansyah** [atomiks/moonlight-vscode-theme#47]
Hello Dev, first of all, I have good experience using this theme while developing React JS, I love it. But not good enough with Vue JS, there's the same color between child components with regular tag HTML, and sometimes makes me confused, could you update the color of child components like in React? 

here's the example 
![sample vue](https://github.com/atomiks/moonlight-vscode-theme/assets/112911127/1a555b8e-b088-49d3-99b2-c90ac65f90f5)

**Comment by atomiks** [comment]
Yeah, this should be yellow like in React

**Comment by RendraAndriansyah** [comment]
> Yeah, this should be yellow like in React

it works when I enabled semantic highlighting
