### ISSUE TITLE
Typescript types not styled sometimes

### ISSUE THREAD

**Issue by MatteoGauthier** [atomiks/moonlight-vscode-theme#48]
Hey ! Love this theme, but I found a visual issue with typescript ⬇️

![image](https://github.com/atomiks/moonlight-vscode-theme/assets/32040951/f60d41ed-524f-49f5-a3fa-018721041878)

**Comment by atomiks** [comment]
I believe this is a problem with VS Code's highlighting engine (TextMate grammar) and not this theme.
