### ISSUE TITLE
How do I get a screenshot with a glowing effect?

### ISSUE THREAD

**Issue by paeonia-lactiflora** [atomiks/moonlight-vscode-theme#50]
![image](https://github.com/atomiks/moonlight-vscode-theme/assets/124262436/8770159d-7e2d-452f-9f8a-8383fec8dfb0)

**Comment by atomiks** [comment]
I'm currently removing references to glows in the upcoming version. The one documented requires a lot of hacks to work compared to how new techniques achieve it (in the Synthwave theme), but I'm not really prepared to investigate how to get it to work myself since I don't bother with it anymore.
