### ISSUE TITLE
What font in preview

### ISSUE THREAD

**Issue by Brettm12345** [atomiks/moonlight-vscode-theme#7]
Hi I would love to know what font is used in the preview

**Comment by atomiks** [comment]
It's the macOS default –– Menlo.

 I suspect it's not really the font you like, but the bold font rendering and high DPI pixel density.

LCD font smoothing (which creates the bold subpixel antialiasing appearance) is disabled in macOS Mojave and greater, you need to turn it on to get the bold characters, which I love for monospace fonts in the editor. http://osxdaily.com/2018/09/26/fix-blurry-thin-fonts-text-macos-mojave/

If you're using Windows, its font rendering is super thin, and, on a low DPI display usually looks poor

**Comment by Brettm12345** [comment]
Thank you
